# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb2bd70cce52fec954b486126077111babaad115cddda245167322e1b04624a55e4807496d7564ac88d10cfe1b76cd1d7800bf874ca2058df15ef43230962d4

test:
  secret_key_base: 8e78980cc5b83e22fcfc17b46600cc1479ff5e2a82d331f951be0d591cd05eb753bbeddcf95b8b5694f347460e374476c437d3cb98f8994a1d594a4ad645a811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
